public with sharing class RefferalsListController {
//
//	@AuraEnabled
//	public static ListViewInfoWrapper getListOfReferrals(
//		String referralSearchText,
//		String sortOrder,
//		String sortField,
//		String filterName
//	) {
//		return new ListViewInfoWrapper(
//			referralSearchText,
//			sortOrder,
//			sortField,
//			'Referral__c',
//			'List_View_Fields',
//			null,
//			filterName
//		);
//	}
}